# GitHub Project Template
# This file can be used to create a project board

name: Settler OSS Development
body: "Project board for tracking Settler OSS development"

# Columns for the project board
columns:
  - name: Backlog
    note: "Ideas and future work"
  - name: To Do
    note: "Ready to start"
  - name: In Progress
    note: "Currently being worked on"
  - name: In Review
    note: "PRs awaiting review"
  - name: Done
    note: "Completed work"

# Labels (will be created if they don't exist)
labels:
  - name: "priority: high"
    color: "b60205"
    description: "High priority"
  - name: "priority: medium"
    color: "d93f0b"
    description: "Medium priority"
  - name: "priority: low"
    color: "fbca04"
    description: "Low priority"
  - name: "good first issue"
    color: "0e8a16"
    description: "Good for new contributors"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention needed"
  - name: "documentation"
    color: "0075ca"
    description: "Documentation related"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
